### PR TITLE
two sum problem completed

### PR DESCRIPTION
**Pull request by vivekmahindrakar**

### CODE REVIEW

**Comment by MayurSMahajan** [comment]
Actually the array is NOT sorted. 
Check the second example : https://leetcode.com/problems/two-sum/

**Comment by vivekmahindrakar** [comment]
If the array is not sorted, we can sort it out ..it would take NLogN and
then apply the same approach


Or we can modify the solution basically we increment or decrement the left
and right pointers according to the upcoming values .

**Comment by MayurSMahajan** [comment]
Vivek my dear, if we sort the array, then how will we return the index of the elements? Have you carefully read the problem statement or not?

Given an array of integers nums and an integer target, return **indices** of the two numbers such that they add up to target.

**Comment by vivekmahindrakar** [comment]
Oh Cmon mayur .....you can just implement vector of vectors where each
vector is a combination of the element and its index and then sort vector
according to the element and then proceed
Time nlogn
Space n

**Comment by MayurSMahajan** [comment]
Implement the solution and then add it to your pull request

**Pull request closed without merging**
